### ISSUE TITLE
Link Not Working

### ISSUE THREAD

**Issue by HarshitVashisht11** [Sahil2004/apratim2k23#4]
When you click on this link this is not working
[sahil2004.github.io/apratim2k23/](https://sahil2004.github.io/apratim2k23/)

**Comment by Sahil2004** [comment]
![image](https://github.com/Sahil2004/apratim2k23/assets/40143545/32a685fa-4bf4-4951-bc94-3ef96ff12c84)
There is no code in this and hence it is empty and not showing anything. The link is thus working fine.
